name: Build IPA-server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout build repository
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Clone IPA-server
      uses: actions/checkout@v4
      with:
        repository: haitrvn/server
        token: ${{ secrets.HAITRVN_TOKEN }}
        path: "server"
        ref: master
    - name: Build Project B
      run: |
        cd server
        chmod +x ./gradlew
        ./gradlew test