name: Build IPA-server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout build repository
      uses: actions/checkout@v3

    - name: Clone IPA-server
      uses: actions/checkout@v4
      with:
        repository: haitrvn/server
        token: ${{ secrets.GITHUB_TOKEN }}
        path: "path/you/want/to/clone/to"
    - name: Build Project B
      run: |
        cd server
        ./gradlew test